//! Tests for rosetta i18n library
//!
//! This crate is only used to test code generated by rosetta-build
//! and does not expose anything useful.

rosetta_i18n::include_translations!();

#[test]
fn test_simple() {
    assert_eq!(Lang::En.hello(), "Hello world!");
    assert_eq!(Lang::Fr.hello(), "Bonjour le monde !");
}

#[test]
fn test_fallback() {
    assert_eq!(Lang::Fr.fallback(), Lang::En.fallback());
}
