[package]
name = "rosetta-test"
version = "0.1.3"
edition = "2018"
license = "ISC"
publish = false

[dependencies]
rosetta-i18n = { path = "../rosetta-i18n" }
static_assertions = "1.1"

[build-dependencies]
rosetta-build = { path = "../rosetta-build" }
